SWAN = {
    "GRAMERCY": "great thanks, from Old French grand merci",
    "QUINCUNX": "five points in a cross, four corners and a centre",
    "SPANDREL": "the triangular space an arch leaves behind",
    "COLOPHON": "the last page of a book, the finishing touch",
    "TREBUCHET": "a counterweight that throws stones at walls",
    "PALIMPSEST": "a page scraped clean, rewritten, traces still showing",
    "ORRERY": "a clockwork model of the planets",
    "CLEPSYDRA": "a water clock, Greek for water thief",
    "CARTOUCHE": "the oval frame around a pharaoh's name",
    "SCRIPTORIUM": "the room where the monks copied manuscripts",
    "INCUNABULA": "books from the cradle of printing, before 1501",
    "MARGINALIA": "notes in the margins",
    "PORTCULLIS": "the sliding gate, porte coulisse",
    "BARBICAN": "the outer gatehouse of a castle",
    "ASTROLABE": "star-taker, for measuring the sky",
    "THEODOLITE": "the angle-measuring instrument surveyors carry",
    "VELLUM": "calfskin stretched into a page",
    "FIRKIN": "a quarter-barrel, from the Dutch for fourth",
    "GAMBREL": "a roof with two slopes per side, the lower one steep",
    "SALTIRE": "the X-shaped cross on Scotland's flag",
    "ZEUGMA": "one word governing two senses at once",
    "MANTICORE": "man-eater, human head, lion body, scorpion tail",
    "CLERESTORY": "the upper windows of a church nave, above the aisle roof",
    "FINIAL": "ornamental cap on a spire or gable peak",
    "LUNETTE": "a half-moon window above a door",
    "PENDENTIVE": "the curved triangle between arches that carries a dome",
    "NARTHEX": "entrance vestibule of a church, where you stand before entering",
    "TRANSEPT": "the crossing arms of a cruciform church",
    "TYMPANUM": "the carved stone above a church doorway",
    "QUOIN": "cornerstone at a building's angle, dressed to show",
    "GNOMON": "the shadow-casting arm of a sundial",
    "ATHANOR": "the self-feeding furnace of the alchemists",
    "PELORUS": "a compass without magnets, for taking bearings by sight",
    "ARMILLARY": "a skeletal globe of celestial rings",
    "SAMITE": "heavy silk of the Middle Ages, shot through with gold",
    "TABARD": "a short open coat bearing a coat of arms",
    "BALDRIC": "a shoulder belt for carrying a sword",
    "GAMBESON": "the padded jacket worn under chain mail",
    "HAUBERK": "a shirt of chain mail reaching the knees",
    "BEZANT": "a gold coin of Byzantium, a gold disk in heraldry",
    "CHIASMUS": "a phrase reversed for effect: ask not what your country",
    "SYNECDOCHE": "the part standing in for the whole",
    "HENDIADYS": "one idea expressed as two words joined by and",
    "TMESIS": "a word split open by another, abso-bloody-lutely",
    "COCKATRICE": "a serpent hatched from a rooster's egg",
    "HIPPOGRIFF": "half horse, half griffin, born of opposites",
    "AMPHISBAENA": "a serpent with a head at each end",
    "SACKBUT": "the ancestor of the trombone",
    "PSALTERY": "a plucked string instrument, the harp of the psalms",
    "REBEC": "a bowed instrument of three strings",
    "THURIBLE": "a censer swung on chains for incense",
    "REREDOS": "an ornamental screen behind an altar",
    "MISERICORD": "the hidden shelf under a choir seat, mercy for standing legs",
    "RELIQUARY": "a vessel for keeping relics of the saints",
    "MONSTRANCE": "the vessel that shows the consecrated host through glass",
    "KILDERKIN": "an eighteen-gallon cask, half a barrel",
    "HOGSHEAD": "a cask of fifty-two gallons",
    "BEZOAR": "a stone from a goat's stomach, once called a cure for poison",
    "HARUSPEX": "one who reads the future in entrails",
    "WYVERN": "a two-legged winged dragon",
    "ESCUTCHEON": "a shield bearing a coat of arms, or the plate around a keyhole",
    "OUBLIETTE": "a dungeon entered only from a trapdoor above",
    "POMANDER": "a ball of perfume carried against plague",
    "PAULDRON": "plate armor for the shoulder",
    "GORGET": "armor for the throat",
    "BALDACHIN": "a canopy over a throne or altar, from Baghdad silk",
    "CALTROP": "spiked iron thrown on the ground to lame horses",
    "MERLON": "the solid tooth of a battlement, between two gaps",
    "RUBRICATION": "red ink for headings in a manuscript",
    "PORTOLAN": "a medieval chart drawn from compass bearings",
    "RHUMB": "a course that crosses every meridian at the same angle",
    "CUCURBIT": "the gourd-shaped vessel at the base of a still",
    "GARDEROBE": "a privy built into a castle wall, hanging over the moat",
    "MACHICOLATION": "floor openings in a battlement for dropping things on attackers",
    "CRENEL": "the gap between two merlons, where archers shoot",
    "BATTLEMENT": "the toothed parapet on a castle wall",
    "LANCET": "a narrow pointed arch, the earliest Gothic window",
    "OGIVE": "the pointed arch of a Gothic vault, two curves meeting",
    "VOUSSOIR": "one wedge-shaped stone in an arch",
    "TRACERY": "the stone ribs dividing a Gothic window into lights",
    "PARGETING": "ornamental plasterwork on a timber-framed wall",
    "TERRAZZO": "a floor of marble chips set in cement, then polished flat",
    "GIRANDOLE": "a branching candleholder mounted on a wall",
    "ASTRAGAL": "a small convex molding at the top of a column",
    "OEILLADE": "a glance thrown sideways, from the French for eye",
    "CENACLE": "a supper room, the upper room of the Last Supper",
    "PHYLACTERY": "a small leather box containing scripture, worn in prayer",
    "SCRIPTURA": "writing as a sacred act, the word made physical",
    "SEDILIA": "stone seats in the south wall of a chancel, for the clergy",
    "CATHEDRA": "the bishop's chair, the thing that makes a cathedral",
    "TONSURE": "the shaved crown of a monk's head",
    "REFECTORY": "the dining hall of a monastery",
    "BREVIARY": "the book of daily prayers a monk carries",
    "PARDONER": "one who sold indulgences, forgiveness for a fee",
    "SENESCHAL": "steward of a great house, the one who runs it",
    "DESTRIER": "a warhorse, led by the right hand into battle",
    "CAPARISON": "the decorated cloth draped over a warhorse",
    "JESSES": "leather straps on a falcon's legs, how the falconer holds on",
    "GAUNTLET": "armored glove, thrown down as a challenge",
    "VAMBRACE": "armor for the forearm",
    "SURCOAT": "the cloth worn over armor, bearing the wearer's arms",
    "PAVISE": "a tall shield a crossbowman stands behind to reload",
    "APSE": "the semicircular end of a church, behind the altar",
    "CHANCEL": "the east end of a church, where the altar stands",
    "CORBEL": "a stone bracket jutting from a wall to carry weight",
    "CUPOLA": "a small dome sitting on a roof like a lantern",
    "PILASTER": "a flat column attached to a wall, for show not strength",
    "SOFFIT": "the underside of an arch, a beam, a staircase",
    "CARYATID": "a column carved as a standing woman",
    "DONJON": "the main tower of a castle, the last refuge",
    "EMBRASURE": "a splayed opening in a wall for shooting through",
    "RAVELIN": "a triangular outwork in front of a fortress gate",
    "GLACIS": "the bare slope before a fortification, swept by fire",
    "BAILEY": "the courtyard inside a castle wall",
    "LOGGIA": "a roofed gallery open on one or more sides",
    "PERISTYLE": "a row of columns surrounding a courtyard or temple",
    "IMPLUVIUM": "the sunken pool in a Roman atrium, catching rain",
    "HYPOCAUST": "Roman underfloor heating, hot air in hollow tiles",
    "PHYSICK": "a medicinal herb garden, where the apothecary grew remedies",
    "STILLROOM": "the room where herbal remedies and cordials were distilled",
    "HERBARIUM": "a collection of plants pressed flat and named",
    "TRENCHER": "a thick slab of bread used as a plate, eaten last",
    "POSSET": "hot milk curdled with wine, drunk against the cold",
    "SYLLABUB": "whipped cream beaten with sweet wine",
    "MARCHPANE": "the old word for marzipan, almond paste and sugar",
    "COMFIT": "a seed or nut coated in layer after layer of sugar",
    "PAVANE": "a slow stately court dance, two steps forward, one back",
    "GALLIARD": "a vigorous Renaissance dance in triple time",
    "SALTARELLO": "a lively Italian dance with jumping steps",
    "ESTAMPIE": "a medieval dance of repeated musical phrases",
    "CHASUBLE": "the outermost vestment worn by a priest at mass",
    "DALMATIC": "a wide-sleeved tunic worn by a deacon",
    "SURPLICE": "a white linen vestment worn over a cassock",
    "AMBO": "a stand for reading scripture, ancestor of the pulpit",
    "TIERCEL": "a male hawk, one third smaller than the female",
    "CREANCE": "the long line tied to a hawk during training",
    "EYASS": "a young hawk taken from the nest before it can fly",
    "MEWS": "the building where hawks are kept while moulting",
    "DEMESNE": "the land a lord keeps for his own table",
    "VILLEIN": "a serf bound to the manor, not free to leave",
    "FEALTY": "the oath of loyalty a vassal swears to a lord",
    "ASSIZES": "the periodic courts held in each county town",
    "SCONCE": "a wall bracket holding a candle or a torch",
    "COFFER": "a strongbox for money, banded with iron",
    "EWER": "a wide-spouted pitcher for washing hands at table",
    "POSTERN": "a small back gate in a castle or city wall",
    "GARNITURE": "a matched set of vases arranged on a mantelpiece",
    "CABOCHON": "a gemstone polished smooth, not cut into facets",
    "INTAGLIO": "a design cut into stone, the reverse of a cameo",
    "NIELLO": "black alloy inlaid into lines engraved in silver",
    "CLOISONNE": "enamel poured between thin soldered metal walls",
    "REPOUSSE": "metalwork shaped by hammering from the back",
    "VERDIGRIS": "the green patina that grows on copper left to weather",
    "KENNING": "an Old English compound metaphor: whale-road for sea",
    "CAESURA": "the pause in the middle of a line of verse",
    "ENJAMBMENT": "a sentence spilling from one verse line to the next",
    "VILLANELLE": "a poem of five tercets and a closing quatrain",
    "SESTINA": "a poem whose six end-words rotate through six stanzas",
    "GHAZAL": "a lyric form of rhyming couplets, each self-contained",
    "DACTYL": "a metrical foot: one long syllable, then two short",
    "SPONDEE": "a metrical foot of two long syllables, heavy and slow",
    "BOWSPRIT": "the spar extending forward from a ship's prow",
    "CAPSTAN": "the vertical drum for winding anchor chain",
    "HAWSER": "a heavy rope for mooring or towing a ship",
    "BOLLARD": "a short iron post on a quay for tying lines to",
    "BINNACLE": "the pedestal that holds the ship's compass",
    "TAFFRAIL": "the rail around the stern of a ship",
    "GUNWALE": "the upper edge of a ship's side, where the guns sat",
    "CARAVEL": "a light fast ship of the age of exploration",
    "FELUCCA": "a lateen-rigged wooden boat of the Mediterranean",
    "XEBEC": "a three-masted vessel with both square and lateen sails",
    "PINNACE": "a small boat carried aboard a larger ship",
    "ADIT": "a horizontal tunnel driven into a hillside to reach ore",
    "STOPE": "the cavern left underground after ore is taken out",
    "WINZE": "a shaft sunk from one mine level to the one below",
    "DORTER": "the sleeping hall of a monastery, above the cloister",
    "GARTH": "the open garden inside a cloister's four walks",
    "LAVABO": "the stone basin where monks washed before meals",
    "CELLARER": "the monk who kept the stores and ran the kitchen",
    "SHAWM": "a loud double-reed instrument of the Middle Ages",
    "CRUMHORN": "a capped reed instrument curved like a shepherd's hook",
    "VIELLE": "a medieval bowed string instrument, ancestor of the violin",
    "CITOLE": "a plucked instrument with a flat back and a holly-leaf shape",
    "TABOR": "a small drum played with one hand while the other pipes",
    "NAKER": "a small kettledrum brought back from the Crusades",
    "DULCIAN": "the Renaissance ancestor of the bassoon",
    "THEORBO": "a bass lute with a second pegbox for long open strings",
    "FAIENCE": "tin-glazed earthenware, named for the city of Faenza",
    "MAJOLICA": "brightly painted Italian pottery with a tin glaze",
    "SAGGAR": "a clay box that shields delicate ware inside the kiln",
    "SENDAL": "a thin silk used for banners and ceremonial linings",
    "FUSTIAN": "a thick twilled cloth of cotton woven with linen",
    "KERSEY": "a coarse ribbed woolen cloth, warm and plain",
    "BUCKRAM": "linen stiffened with paste, used for bookbinding",
    "PILCROW": "the paragraph mark, from the Greek paragraphos",
    "OBELUS": "the dagger mark, set beside doubtful passages",
    "MANICULE": "the pointing hand drawn in manuscript margins: read this",
    "HEDERA": "the ivy leaf printers set between paragraphs",
    "HALBERD": "a pole weapon combining an axe blade and a spike",
    "GLAIVE": "a single-edged blade mounted on a long pole",
    "FALCHION": "a broad curved sword, heavier toward the point",
    "FLAMBERGE": "a two-handed sword with a wavy, flame-shaped blade",
    "ARBALEST": "a heavy crossbow drawn with a windlass or cranequin",
    "BASCINET": "a pointed helmet that covers the face with a visor",
    "SALLET": "a helmet with a tail to guard the back of the neck",
    "MORION": "a helmet with a high comb and a wide brim, open-faced",
    "RONDEL": "a dagger with disc guards, for finding gaps in armor",
    "BARDICHE": "a long-handled axe with a cleaver-shaped blade",
    "QUILLON": "the crossguard of a sword, protecting the hand",
    "CHANFRON": "plate armor shaped to a horse's face",
    "PEYTRAL": "armor for a horse's chest, hung from the saddle",
    "OSSUARY": "a vault for storing the bones of the dead",
    "CATAFALQUE": "a raised platform bearing a coffin in state",
    "CENOTAPH": "a monument to someone whose body lies elsewhere",
    "DOLMEN": "a megalithic tomb: two standing stones and a capstone",
    "MENHIR": "a single tall standing stone, older than memory",
    "CROMLECH": "a ring of standing stones",
    "CALDARIUM": "the hot room of a Roman bath",
    "TEPIDARIUM": "the warm room of a Roman bath, for lingering",
    "FRIGIDARIUM": "the cold plunge of a Roman bath",
    "WAINSCOT": "oak paneling on the lower walls of a room",
    "ACANTHUS": "the spiny leaf carved on Corinthian column capitals",
    "SERAGLIO": "the sequestered quarters of a palace",
    "TRILITHON": "two standing stones bearing a lintel, a doorway to nowhere",
    "PASSANT": "walking, as a lion is drawn on a coat of arms",
    "GULES": "heraldic red, from the French for a throat",
    "FESS": "a horizontal band across the middle of a shield",
    "VOULGE": "a broad cleaving blade on a six-foot pole",
    "PARTISAN": "a broad-bladed spear with lateral projections",
    "EPHEMERIS": "a table of where the planets will be, day by day",
    "PLANISPHERE": "a rotating star map held flat against the sky",
    "ADZE": "a woodworking blade set at right angles to the handle",
    "COIF": "a close-fitting cap of linen or chain mail",
    "KIRTLE": "a long garment worn by men and women, belted at the waist",
    "POTTAGE": "thick vegetable soup, the daily meal of the poor",
    "CAUDLE": "a warm spiced drink given to the sick and the newly delivered",
    "ASHLAR": "stone cut square and smooth, dressed for a fine wall",
    "SGRAFFITO": "decoration made by scratching through a layer of plaster",
    "MINARET": "the tower of a mosque, from which the call to prayer is given",
    "MUQARNAS": "honeycomb vaulting in Islamic architecture, geometry made solid",
    "ELECTUARY": "a medicine mixed with honey to make it go down",
    "THERIAC": "an ancient universal antidote compounded of dozens of ingredients",
    "DECOCTION": "a remedy made by boiling herbs until the water carries them",
    "CATAPLASM": "a poultice of herbs and meal laid hot on the skin",
    "NOSTRUM": "a quack remedy, from the Latin: it is ours",
    "TREFOIL": "a three-lobed ornament, the shape of a clover leaf",
    "QUATREFOIL": "a four-lobed ornament, each lobe a rounded arch",
    "CINQUEFOIL": "a five-lobed ornament, five petals of stone",
    "CROCKET": "a hooked leaf carved along the edge of a Gothic spire",
    "VOLUTE": "the spiral scroll on an Ionic capital, wound like a shell",
    "ABACUS": "the flat slab on top of a column capital, carrying the beam",
    "ACROTERION": "an ornament at the peak or edge of a pediment",
    "ANTEFIX": "an upright ornament at the eaves, hiding the tile ends",
    "DENTIL": "a small rectangular block in a row under a cornice, like teeth",
    "METOPE": "the panel between two triglyphs in a Doric frieze",
    "TRIGLYPH": "the grooved tablet alternating with metopes in a Doric frieze",
    "ARCHITRAVE": "the lowest band of an entablature, resting on the columns",
    "ENTABLATURE": "the horizontal structure above columns: architrave, frieze, cornice",
    "PLINTH": "the square base under a column or a statue",
    "STYLOBATE": "the top step of a temple platform, where the columns stand",
    "CREPIDOMA": "the stepped platform of a Greek temple",
    "NAOS": "the inner chamber of a Greek temple, where the statue stood",
    "PRONAOS": "the porch in front of the naos",
    "OPISTHODOMOS": "the room at the back of a Greek temple, used as a treasury",
    "OCULUS": "the round opening at the top of a dome, open to the sky",
    "LANTERN": "a windowed turret crowning a dome, letting in light",
    "ROTUNDA": "a circular building or room, usually domed",
    "SQUINCH": "an arch across an interior corner, turning a square into an octagon for a dome",
    "GROIN": "the sharp edge where two barrel vaults cross",
    "LIERNE": "a short decorative rib in a Gothic vault, connecting the main ribs",
    "TIERCERON": "a secondary rib springing from the same point as the main ones",
    "BOSKET": "a thicket of trees in a formal garden, trimmed to a wall",
    "PARTERRE": "a level garden area with beds in a geometric pattern",
    "KNOT": "a garden bed of interlacing low hedges, the Tudor kind",
    "ORANGERY": "a building with tall windows for growing citrus through winter",
    "DOVECOTE": "a small tower with nesting holes for pigeons",
    "LYCHGATE": "a roofed gate at the entrance to a churchyard",
    "SNICKET": "a narrow path between walls or fences, a northern English word",
    "WYND": "a narrow lane turning off a main street, the Scottish word",
    "GINNEL": "a narrow passage between buildings, the Yorkshire word",
    "VENNEL": "a narrow lane, the Scots word for the same thing",
    "CLOSE": "a passage leading from the street to a common yard behind the houses",
    "PEND": "a covered passage through a building, the Scottish kind",
    "CAUL": "a close-fitting cap of netting, worn under a headdress",
    "WIMPLE": "a cloth covering the head, chin and neck, worn by nuns",
    "FARTHINGALE": "a hooped petticoat that holds the skirt wide",
    "CHOPINE": "a platform shoe of the Renaissance, sometimes a foot tall",
    "POULAINE": "the long pointed toe of a medieval shoe",
    "HENNIN": "a tall conical headdress with a trailing veil",
    "BLIAUT": "a long fitted gown of the 12th century, laced at the sides",
    "CYCLAS": "a sleeveless surcoat worn over armor",
    "SURCOTE": "an outer garment worn over the cotte, open at the sides",
    "JUPON": "a tight-fitting padded garment worn over armor",
    "BRIGANDINE": "a coat of small plates riveted inside cloth",
    "CUIRASS": "a breastplate and backplate buckled together",
    "SABATON": "plate armor for the foot, articulated at the toes",
    "SOLLERET": "a pointed shoe of plate armor, hinged to walk in",
    "BEVOR": "plate armor protecting the chin and throat",
    "ARMET": "a close-fitting helmet that opens on hinges to put on",
    "BARBUTE": "a helmet shaped like an ancient Greek one, open-faced",
    "KETTLE": "a round helmet like an upturned pot, the simplest kind",
    "SPANGENHELM": "a helmet made of metal strips riveted to plates",
    "NASAL": "the strip of metal protecting the nose on an early helmet",
    "AILETTE": "a small shield worn on the shoulder, for identification",
    "FAULD": "the skirt of plates hanging from a breastplate",
    "TASSET": "a plate hanging from the fauld to protect the upper thigh",
    "PLACKART": "an extra plate bolted to the lower breastplate",
    "BESAGEW": "a small round plate protecting the armpit",
    "COUTER": "plate armor for the elbow",
    "POLEYN": "plate armor for the knee",
    "REREBRACE": "armor for the upper arm",
    "GARDEBRAS": "an extra plate bolted over the rerebrace",
    "CHAMFRAIN": "plate armor shaped to a horse's face, with eye guards",
    "TESTIERE": "armor for the top of a horse's head",
    "CRUPPER": "a strap under a horse's tail to keep the saddle from sliding",
    "CANTLE": "the raised back of a saddle",
    "TRAPPER": "a cloth covering a horse from ears to tail",
    "SHABRACK": "an ornamental saddlecloth, usually fringed",
    "MARTINGALE": "a strap from the girth to the noseband to keep a horse's head down",
    "CURVET": "a movement where a horse leaps with forelegs raised",
    "PIAFFE": "a trot in place, the horse lifting its feet without advancing",
    "LEVADE": "a controlled rear, the horse balanced on bent hind legs",
    "CAPRIOLE": "a leap in which the horse kicks out at the height of the jump",
    "PASSADE": "a turn on the haunches, reversing direction in a fight",
    "CARACOLE": "a half-turn performed by a mounted troop, wheel and fire",
    "MANEGE": "the art of training horses, or the arena where it happens",
    "VOLTIGE": "acrobatics performed on a moving horse",
    "HIPPODROME": "a course for horse races, from the Greek for horse and track",
    "TILTYARD": "the enclosed ground where jousts were held",
    "QUINTAIN": "a rotating target for lance practice, it hits back if you are slow",
    "PELL": "a wooden post for sword practice",
    "HOURD": "a temporary wooden gallery built out from a castle wall for defense",
    "CHEVAUCHEE": "a destructive raid through enemy territory, burning as it goes",
    "CHEVAUCHER": "to ride on such a raid",
    "COURSER": "a swift horse bred for running and carrying messages",
    "PALFREY": "a riding horse for everyday travel, gentle-gaited",
    "JENNET": "a small Spanish horse, light and nimble",
    "HACKNEY": "a horse for ordinary riding, not war",
    "ROUNCEY": "a general-purpose horse, the common soldier's mount",
    "SUMPTER": "a packhorse, carrying baggage and supplies",
    "CHARGER": "a horse trained for battle, ridden into the charge",
    "GABION": "a basket filled with earth, stacked to make a wall under fire",
    "PONTIL": "the iron rod used to hold a glass vessel while it is shaped",
    "CLAYMORE": "the great two-handed sword of the Scottish Highlands",
    "PONIARD": "a light dagger for the left hand, used to parry",
    "TARGE": "a small round shield, carried on the arm",
    "MISSAL": "the book containing the prayers and readings for mass",
    "GRADUAL": "the chant sung between the epistle and the gospel",
    "ANTIPHON": "a verse sung as a response, one choir answering another",
    "RESPONSORY": "a chant in which the soloist and the choir alternate",
}
